
pool:
  vmImage: 'windows-2019'

steps:
- task: GitVersion@4
  displayName: Git Version
  inputs:
    updateAssemblyInfo: false

- task: DotNetCoreCLI@2
  displayName: Build Projects
  inputs:
    command: build
    projects: '**/*.sln'

- task: PowerShell@2
  displayName: Update TemplateVersion props
  inputs:
    filePath: 'build/Update-TemplateVersions.ps1'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '>= 5.4'
    checkLatest: true

- task: NuGetCommand@2
  displayName: NuGet Pack
  inputs:
    command: pack
    packagesToPack: src/NV.Templates.nuspec
    packDestination: $(build.artifactStagingDirectory)
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersionV2

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'

- task: NuGetCommand@2
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('true', variables['forcePushNuget'])))
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/**/*.nupkg;!$(build.artifactStagingDirectory)/**/*.snupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nventive'
